name: Publish Docker to ECR
description: Build and publioshed docker image to ECR
author: itsmycargo
branding:
  color: blue
  icon: layers

inputs:
  name:
    description: Project Name for Deployment
    required: true
  environment:
    description: Environment Name for Deployment
    required: true
  domain:
    description: Domain for deployment environment
    required: true

outputs:
  name:
    description: Deploy name for branch/environment
  url:
    description: URL for deployment

runs:
  using: node12
  main: index.js
